name: Call a reusable workflow 

on:
  workflow_dispatch:
    inputs:
      client_repository:
        description: 'repository'
      branch:
        description: 'branch'
      user_id:
        description: 'user_id'

 
jobs:

  Deploy:
    
    uses: American-Chip/workflow-remote/.github/workflows/graviton-scan-reusable.yaml@develop
    with:
      CLIENT_REPOSITORY: ${{ inputs.client_repository }}
      BRANCH : ${{ inputs.branch }}
      USER_id : ${{ inputs.user_id }}

    secrets:
      ac_github_token: ${{secrets.Token_WF}}
